### ISSUE TITLE
Add list of open Cosmos Hub RPC / LCD endpoints

### ISSUE THREAD

**Issue by dogemos** [cosmos/awesome#17]
One of the most repeatedly asked question for developers is a list of openly available RPC endpoints and APIs. I'd really like to compile a list of open endpoints that delegators / developers can use to connect their `gaiacli` or query on-chain data.

I'm going to create an initial list of a few that I'm aware of:

RPC
- `https://cosmoshub.validator.network:443`
- `https://cosmos.chorus.one:26657`
- `https://rpc.cosmos.network:26657`

LCD / REST
- `https://lcd-do-not-abuse.cosmostation.io/`
- `https://stargate.cosmos.network/`

Feel free to add any others that are not on the list yet.

**Comment by jackzampolin** [comment]
This is a great list @dogemos! 👏

**Comment by marbar3778** [comment]
I think this may be the wrong repo to host this information. I think the bottom of the gaia readme or a .md file in the gaia repo would be best

**Comment by dogemos** [comment]
Got it.

My thought was to compile a list for commonly asked resources such as endpoints, javascript libraries, etc. What would be the best way of approaching this? Would a `resources.md` within make sense or will adding it to `readme.md` be better? 

I figured we'd also need to add a warning that most of these are community-driven resources that haven't been audited.

**Comment by EugeneTeu** [comment]
hey guys looking for publicily available API to parse cosmos transactions, is there a reliable available one now other than running our own node? @dogemos

**Comment by akshitv1** [comment]
@EugeneTeu I am looking for it as well, any luck of finding one ?

**Comment by EugeneTeu** [comment]
Hey @akshitv1 , no luck, will be running our own node for the sub chains since its the most reliable for my use case

> @EugeneTeu I am looking for it as well, any luck of finding one ?

**Comment by akshitv1** [comment]
> Hey @akshitv1 , no luck, will be running our own node for the sub chains since its the most reliable for my use case
> 
> > @EugeneTeu I am looking for it as well, any luck of finding one ?

Hi @EugeneTeu i found one url that i am using to transfer funds 'https://api.cosmos.network'. Is this not reliable ? Should i be worried about safety of my wallet, if i am using this?

**Comment by EugeneTeu** [comment]
> > Hey @akshitv1 , no luck, will be running our own node for the sub chains since its the most reliable for my use case
> > > @EugeneTeu I am looking for it as well, any luck of finding one ?
> 
> Hi @EugeneTeu i found one url that i am using to transfer funds 'https://api.cosmos.network' (https://v1.cosmos.network/rpc/v0.41.4). Is this not reliable ? Should i be worried about safety of my wallet, if i am using this?

hey yea @akshitv1 , should totally be ok since its hosted by the team (if im not mistaken). the reliability im referring to is whether the API is able to handle spikes in loads etc..

**Comment by sunnya97** [comment]
@akshitv1 @EugeneTeu you guys can get access to free endpoints from Figment's DataHub platform.

https://datahub.figment.io/services/cosmos

Just make an account, it will give you an API key

**Comment by victor-wei126** [comment]
Are these public endpoints through which we can send transactions to? Like how Infura provides a set of nodes and then wallets can send a transaction to them. I am trying to build a wallet and need a way to broadcast Cosmos transactions.

**Comment by dogemos** [comment]
You should assume most of these endpoints are primarily for testing purposes, without uptime/load guarantees.

For more production-level infrastructure, please operate your own endpoint or use one of the following services:
- https://www.allthatnode.com/
- https://datahub.figment.io/
- https://www.coinbase.com/cloud/blockchain-infrastructure
- and more
