### ISSUE TITLE
Add fissionlabsio/juno

### ISSUE THREAD

**Issue by kochetkov-av** [cosmos/awesome#43]
Not sure where to put this tool, but it definitely should be in list

Cosmos Hub data aggregator, with Postgres and GraphQl api:
https://github.com/fissionlabsio/juno

Author mentioned, that he is not planning to maintain service for free for much longer, but for now it here:
https://gaiaql.fissionlabs.io/

**Comment by julienrbrt** [comment]
The project seems not unmaintained. Closing. Please don't hesitate to re-open this issue if deemed necessary.
