### ISSUE TITLE
add sharering

### ISSUE THREAD

**Issue by hxrts** [cosmos/awesome#62]
https://github.com/ShareRing/Shareledger

**Comment by lovincyrus** [comment]
Sharering exists in [cosmonauts.world](https://github.com/lovincyrus/cosmonauts-world/blob/master/data/posts-manifest.js#L616) already. Do you prefer it to be added under https://github.com/cosmos/awesome#ecosystem as well? @hxrts

**Comment by hxrts** [comment]
hoping these will be unified at some point soon! just adding things here as I find them.
