### ISSUE TITLE
add white city

### ISSUE THREAD

**Issue by hxrts** [cosmos/awesome#75]
https://github.com/KZen-networks/white-city

**Comment by marbar3778** [comment]
I don't think this has anything to do with cosmos? Should we be adding things that are specifically tendermint to cosmos/awesome?

**Comment by hxrts** [comment]
good question. is the [Awesome Tendermint](https://github.com/tendermint/awesome) repo maintained at all? need to think more carefully about that property.

**Comment by julienrbrt** [comment]
Closing. Please don't hesitate to re-open this issue if deemed necessary.
