### ISSUE TITLE
[QUESTION] Live IBC bridges

### ISSUE THREAD

**Issue by arnabghose997** [cosmos/awesome#99]
Hello Team, the Bridge section of Readme.md has only 3 bridges. Are there any more bridges that needs to be included in the list, especially the ones which are currently live? Thanks in advance.

**Comment by ethanfrey** [comment]
Those are Rust bridges, not just IBC (nomic is a sidechain).

I think wormhole would deserve to be there, as it does integrate a cosmos chain (terra) and other's look at it.
Also, Peggy or the various Ethereum bridges out there.

I don't have links to those teams, but second your point.

**Comment by arnabghose997** [comment]
Hey @ethanfrey , appreciate your response for my query!
